{% set name = "twython" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6ca64309260e0ab47267f76217c80812f591991437f376fc61498816384f9e7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - requests >=2.1.0
    - requests-oauthlib >=0.4.0

test:
  imports:
    - twython
    - twython.streaming
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ryanmcgrath/twython/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Actively maintained, pure Python wrapper for the Twitter API. Supports both normal and streaming Twitter APIs'
  dev_url: https://github.com/ryanmcgrath/twython/
  doc_url: https://twython.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
