{% set name = "twython" %}
{% set version = "3.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "24ae29b4dd8d69df81707eb5fb7a1babd6689a3d69cd618f0647997d6179d338" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - requests >=2.1.0
    - requests-oauthlib >=0.4.0

test:
  imports:
    - twython
    - twython.streaming

about:
  home: https://github.com/ryanmcgrath/twython/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Actively maintained, pure Python wrapper for the Twitter API. Supports both normal and streaming Twitter APIs'
  dev_url: https://github.com/ryanmcgrath/twython/
  doc_url: https://twython.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
