{% set name = "twython" %}
{% set version = "3.8.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "145c07af6dede60906efa16b1d9648d830194833b2684a97e96b196b3250c8b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - requests >=2.1.0
    - requests-oauthlib >=0.4.0

test:
  imports:
    - twython
    - twython.streaming

about:
  home: https://github.com/ryanmcgrath/twython/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Actively maintained, pure Python wrapper for the Twitter API. Supports both normal and streaming Twitter APIs
  dev_url: https://github.com/ryanmcgrath/twython/
  doc_url: https://twython.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
